/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/head-of-michelangelos-david-optimised-d29af50360624e5e9b1855666475380d
Title: Head Of Michelangelo's David, Optimised
*/
"use client"
import { useGLTF } from '@react-three/drei'
import { useRef,useState,useEffect } from 'react'
import { useBox } from '@react-three/cannon'

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "models/head_of_michelangelos_david_optimised.glb"
  );
  const group = useRef()
  const [boxRef,boxApi] = useBox(() => ({ mass: 1000, position: [0.7,7, 1.2]}))
  // hover
  const [hovered, setHovered] = useState(false)
  
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
    return () => document.body.style.cursor = 'auto';        
}, [hovered])
  
  return (
    <group     
      castShadow
      receiveShadow
      position={[0.7,-1.5,1.2]}
      scale={0.015}
      ref={node => {
        group.current = node,
        boxRef.current = node
      }}
    onClick={() => { boxApi.velocity.set(0,2,0) }}  
    dispose={null} 
    onPointerOver={() => setHovered(true)}  onPointerOut={() => setHovered(false)}
    
>
        <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}

        rotation={[-Math.PI, -1.282, -0.011]}
      />
    </group>
  );
}

useGLTF.preload("models/head_of_michelangelos_david_optimised.glb");