/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export function Fracture(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/head_fracture.glb");
  const { actions } = useAnimations(animations, group);
  

  useEffect(() => {
    
    Object.keys(actions).forEach((key) => {
      console.log(actions[key])
      actions[key].setLoop( THREE.LoopOnce )  
      actions[key].clampWhenFinished = true;
      actions[key].play();
      
      });

  });
  
  return (
    <group ref={group} {...props} dispose={null} 
    >
      <group name="Scene">
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes"
          position={[103.372, 119.332, 124.479]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes100_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes100_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes100_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes100_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes001"
          position={[106.305, 129.684, 89.135]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes101"
            castShadow
            receiveShadow
            geometry={
              nodes["appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes101"]
                .geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes101_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes101_1"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes002"
          position={[114.875, 167.578, 108.217]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes001_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes001_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes001_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes001_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes003"
          position={[87.006, 92.836, 144.931]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes002_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes002_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes002_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes002_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes004"
          position={[53.004, 144.537, 143.468]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes003_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes003_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes003_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes003_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes005"
          position={[81.8, 148.166, 141.149]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes004_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes004_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes004_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes004_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes006"
          position={[114.865, 135.436, 119.71]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes005_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes005_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes005_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes005_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes007"
          position={[100.36, 107.861, 88.939]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes006_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes006_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes006_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes006_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes008"
          position={[25.026, 178.803, 112.822]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes007_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes007_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes007_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes007_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes009"
          position={[111.518, 141.261, 125.502]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes008_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes008_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes008_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes008_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes010"
          position={[8.36, 156.717, 120.153]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes009_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes009_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes009_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes009_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes011"
          position={[116.687, 145.974, 100.214]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes010_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes010_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes010_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes010_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes012"
          position={[45.076, 186.711, 127.97]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes011_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes011_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes011_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes011_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes013"
          position={[70.126, 79.051, 118.362]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes012_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes012_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes012_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes012_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes014"
          position={[62.986, 128.698, 90.726]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes013_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes013_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes013_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes013_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes015"
          position={[65.999, 186.378, 107.377]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes014_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes014_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes014_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes014_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes016"
          position={[31.957, 136.176, 105.378]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes015_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes015_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes015_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes015_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes017"
          position={[110.264, 81.86, 80.177]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes016_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes016_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes016_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes016_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes018"
          position={[83.241, 185.692, 128.374]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes017_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes017_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes017_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes017_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes019"
          position={[11.888, 164.475, 142.629]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes018_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes018_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes018_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes018_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes020"
          position={[119.072, 144.057, 116.266]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes019_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes019_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes019_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes019_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes021"
          position={[41.876, 149.232, 80.935]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes020_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes020_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes020_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes020_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes022"
          position={[78.817, 154.439, 144.182]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes021_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes021_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes021_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes021_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes023"
          position={[13.057, 154.265, 113.177]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes022_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes022_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes022_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes022_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes024"
          position={[73.871, 174.754, 86.41]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes023_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes023_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes023_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes023_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes025"
          position={[120.417, 103.355, 102.623]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes024_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes024_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes024_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes024_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes026"
          position={[100.74, 130.836, 127.153]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes025_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes025_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes025_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes025_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes027"
          position={[108.179, 169.289, 97.463]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes026_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes026_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes026_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes026_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes028"
          position={[36.757, 163.248, 146.933]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes027_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes027_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes027_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes027_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes029"
          position={[25.524, 151.323, 94.182]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes028_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes028_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes028_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes028_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes030"
          position={[71.288, 118.263, 88.969]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes029_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes029_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes029_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes029_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes031"
          position={[46.628, 146.681, 88.793]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes030_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes030_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes030_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes030_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes032"
          position={[51.951, 116.563, 103.6]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes031_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes031_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes031_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes031_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes033"
          position={[117.1, 151.357, 125.101]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes032_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes032_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes032_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes032_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes034"
          position={[68.159, 57.828, 103.416]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes033_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes033_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes033_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes033_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes035"
          position={[46.092, 142.985, 95.647]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes034_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes034_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes034_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes034_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes036"
          position={[19.314, 150.009, 104.261]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes035_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes035_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes035_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes035_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes037"
          position={[120.984, 85.477, 105.913]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes036_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes036_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes036_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes036_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes038"
          position={[89.339, 157.126, 81.87]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes037_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes037_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes037_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes037_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes039"
          position={[118.091, 86.485, 124.487]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes038_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes038_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes038_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes038_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes040"
          position={[76.515, 64.776, 92.135]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes039_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes039_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes039_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes039_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes041"
          position={[91.728, 169.017, 144.862]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes040_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes040_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes040_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes040_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes042"
          position={[85.024, 64.592, 77.435]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes041_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes041_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes041_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes041_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes043"
          position={[89.477, 139.65, 82.94]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes042_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes042_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes042_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes042_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes044"
          position={[94.166, 143.644, 133.2]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes043_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes043_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes043_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes043_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes045"
          position={[118.155, 110.037, 114.838]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes044_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes044_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes044_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes044_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes046"
          position={[82.583, 119.989, 82.406]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes045_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes045_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes045_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes045_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes047"
          position={[71.437, 71.955, 108.958]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes046_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes046_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes046_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes046_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes048"
          position={[113.699, 55.234, 112.407]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes047_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes047_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes047_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes047_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes049"
          position={[35.675, 123.5, 128.96]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes048_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes048_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes048_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes048_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes050"
          position={[93.872, 75.146, 85.459]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes049_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes049_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes049_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes049_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes051"
          position={[42.922, 120.965, 137.424]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes050_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes050_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes050_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes050_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes052"
          position={[72.84, 60.083, 133.69]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes051_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes051_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes051_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes051_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes053"
          position={[111.068, 114.159, 89.276]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes052_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes052_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes052_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes052_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes054"
          position={[60.946, 99.015, 114.745]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes053_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes053_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes053_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes053_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes055"
          position={[83.202, 72.018, 134.263]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes054_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes054_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes054_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes054_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes056"
          position={[25.913, 158.628, 88.891]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes055_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes055_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes055_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes055_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes057"
          position={[101.579, 93.924, 137.277]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes056_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes056_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes056_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes056_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes058"
          position={[83.031, 80.36, 96.811]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes057_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes057_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes057_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes057_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes059"
          position={[105.595, 156.034, 135.055]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes058_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes058_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes058_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes058_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes060"
          position={[104.061, 137.571, 127.11]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes059_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes059_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes059_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes059_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes061"
          position={[96.556, 182.273, 110.565]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes060_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes060_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes060_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes060_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes062"
          position={[33.211, 164.716, 87.233]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes061_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes061_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes061_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes061_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes063"
          position={[20.068, 149.181, 125.734]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes062_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes062_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes062_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes062_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes064"
          position={[87.849, 155.543, 138.356]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes063_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes063_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes063_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes063_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes065"
          position={[76.358, 157.183, 148.485]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes064_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes064_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes064_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes064_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes066"
          position={[54.197, 166.217, 151.524]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes065_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes065_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes065_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes065_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes067"
          position={[80.352, 113.176, 132.745]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes066_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes066_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes066_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes066_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes068"
          position={[59.271, 186.124, 133.025]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes067_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes067_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes067_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes067_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes069"
          position={[57.245, 153.684, 76.457]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes068_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes068_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes068_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes068_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes070"
          position={[112.933, 94.009, 145.26]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes069_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes069_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes069_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes069_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes071"
          position={[101.059, 58.169, 102.636]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes070_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes070_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes070_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes070_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes072"
          position={[50.195, 137.766, 87.988]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes071_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes071_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes071_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes071_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes073"
          position={[22.482, 165.042, 146.355]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes072_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes072_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes072_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes072_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes074"
          position={[120.658, 132.82, 110.142]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes073_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes073_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes073_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes073_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes075"
          position={[81.295, 95.178, 92.819]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes074_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes074_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes074_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes074_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes076"
          position={[117.613, 123.427, 118.217]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes075_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes075_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes075_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes075_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes077"
          position={[110.908, 157.352, 93.22]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes076_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes076_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes076_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes076_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes078"
          position={[6.844, 163.573, 115.142]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes077_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes077_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes077_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes077_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes079"
          position={[30.765, 145.706, 136.25]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes078_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes078_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes078_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes078_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes080"
          position={[66.868, 78.068, 149.913]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes079_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes079_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes079_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes079_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes081"
          position={[105.864, 56.273, 125.011]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes080_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes080_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes080_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes080_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes082"
          position={[115.399, 101.096, 96.308]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes081_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes081_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes081_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes081_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes083"
          position={[46.029, 133.648, 97.836]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes082_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes082_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes082_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes082_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes084"
          position={[67.535, 133.715, 80.623]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes083_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes083_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes083_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes083_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes085"
          position={[85.944, 82.064, 145.244]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes084_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes084_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes084_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes084_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes086"
          position={[28.282, 139.76, 126.237]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes085_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes085_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes085_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes085_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes087"
          position={[14.382, 159.91, 134.268]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes086_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes086_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes086_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes086_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes088"
          position={[50.96, 142.804, 83.117]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes087_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes087_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes087_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes087_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes089"
          position={[44.419, 173.964, 88.586]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes088_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes088_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes088_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes088_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes090"
          position={[73.565, 183.947, 138.994]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes089_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes089_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes089_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes089_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes091"
          position={[40.507, 149.854, 89.862]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes090_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes090_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes090_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes090_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes092"
          position={[11.427, 174.454, 135.411]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes091_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes091_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes091_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes091_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes093"
          position={[97.729, 163.144, 139.7]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes092_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes092_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes092_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes092_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes094"
          position={[109.674, 170.607, 127.702]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes093_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes093_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes093_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes093_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes095"
          position={[120.965, 119.422, 99.948]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes094_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes094_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes094_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes094_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes096"
          position={[119.947, 109.674, 96.316]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes095_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes095_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes095_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes095_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes097"
          position={[35.744, 145.948, 99.044]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes096_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes096_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes096_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes096_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes098"
          position={[73.68, 167.634, 149.651]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes097_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes097_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes097_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes097_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes099"
          position={[16.309, 172.673, 137.606]}
          rotation={[-1.63, 0, 0]}
          scale={[1, 0.699, 0.699]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes098_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes098_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes098_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes098_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>
        <group
          name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes100"
          position={[107.786, 106.579, 130.389]}
        >
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes099_1"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes099_1"
              ].geometry
            }
            material={materials.material_0}
          />
          <mesh
            name="appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes099_2"
            castShadow
            receiveShadow
            geometry={
              nodes[
                "appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes099_2"
              ].geometry
            }
            material={materials.inside}
          />
        </group>

      </group>
    </group>
  );
}

useGLTF.preload("models/head_fracture.glb");


/**
 *         <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[84.363, -1, 101.453]}
          scale={[3.235, 1.906, 2.581]}
        /> 
 * 
 * 
 * 
 */