"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shinymagic (https://sketchfab.com/shinymagic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/backup-looking-glass-display-concept-1-0da1f07443154eaf8116957fe86e5247
Title: backup_looking glass display Concept 1
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";


export function Cube(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../models/cube.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 001"].play();
  });

  return (
    <group ref={group} scale={7} position={[4,2,0]} rotation={[0,0,Math.PI /2]} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="f47c798a7f48467594bdaac01dc67e91fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Concept_202"
                  position={[0, 0.152, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  
                  <group name="Concept_203" rotation={[0, Math.PI / 2, 0]}>
                    <group name="Object_6" position={[-0.036, 0.072, -507.334]}>
                      <mesh
                        name="Concept_203_hexagon__0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Concept_203_hexagon__0.geometry}
                        material={materials.hexagon}
                      >
                                       
                      </mesh>
                      <mesh
                        name="Concept_203_glowing_edges_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Concept_203_glowing_edges_0.geometry}
                        material={materials.glowing_edges}
                      >
                      <meshStandardMaterial
                      emissive={"#ec4899"}
                      emissiveIntensity={10}
                      wireframe={true}
                      toneMapped={false}
                      />
                        </mesh>
                    </group>
                  </group>
                  
                  <group
                    name="Concept_2_orange_line01"
                    position={[7.689, 0, 0]}
                    rotation={[0.087, 1.571, 0]}
                  >
                    <group
                      name="Object_10"
                      position={[-0.036, 0.072, -507.334]}
                    >
                      <mesh
                        name="Concept_2_orange_line01_thin_line_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Concept_2_orange_line01_thin_line_0.geometry
                        }
                        material={materials.thin_line}
                      >                        
                      <meshStandardMaterial
                      emissive={"#ec4899"}
                      emissiveIntensity={6}
                      toneMapped={false}
                    /></mesh>
                    </group>                   
                  </group>
                </group>
                <group
                  name="Concept_201"
                  position={[0, 0.152, 0]}
                  rotation={[0.698, 0, -Math.PI / 4]}
                  scale={0.005}
                >
                  <group name="Object_13" position={[0, 0, -12.5]}>
                    <mesh
                      name="Concept_201_blue_cube_mapped_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Concept_201_blue_cube_mapped_0.geometry}
                      material={materials.blue_cube_mapped}
                    >

                    </mesh>
                  </group>
                </group>
                
                
                <group
                  name="Plane002"
                  position={[-0.819, 0.167, -0.003]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_16"
                    position={[532.114, 0, -38.875]}
                    rotation={[Math.PI / 2, 0, 1.52]}
                  >
                    <mesh
                      name="Plane002_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane002_volume_light_0.geometry}
                      material={materials.volume_light}
                    >                 
                    </mesh>
                  </group>
                </group>
                
                <group
                  name="Concept_204"
                  position={[0, 0.152, 0]}
                  rotation={[0.698, 0, -Math.PI / 4]}
                  scale={0.006}
                >
                  <group name="Object_19" position={[0, 0, -12.5]}>
                    <mesh
                      name="Concept_204_blue_cube_mapped_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Concept_204_blue_cube_mapped_0.geometry}
                      material={materials.blue_cube_mapped}
                    >
                    <meshStandardMaterial
                      emissive={"#9d174d"}
                      emissiveIntensity={20}
                      toneMapped={false}
                    />

                    </mesh>
                  </group>
                </group>
                <group
                  name="Plane004"
                  position={[-0.819, 0.168, -0.003]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_22"
                    position={[532.598, -21.397, 16.451]}
                    rotation={[1.572, -0.04, 1.602]}
                  >
                    <mesh
                      name="Plane004_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane004_volume_light_0.geometry}
                      material={materials.volume_light}
                    />
                  </group>
                </group>
                <group
                  name="Plane005"
                  position={[0.879, 0.143, -0.003]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_25"
                    position={[-533.066, 14.955, -16.481]}
                    rotation={[-1.57, 0.028, -1.58]}
                  >
                    <mesh
                      name="Plane005_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane005_volume_light_0.geometry}
                      material={materials.volume_light}
                    />
                  </group>
                </group>
                <group
                  name="Plane006"
                  position={[0.879, 0.143, -0.003]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_28"
                    position={[-532.464, 0, 29.508]}
                    rotation={[-Math.PI / 2, 0, -1.515]}
                  >
                    <mesh
                      name="Plane006_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane006_volume_light_0.geometry}
                      material={materials.volume_light}
                    />
                  </group>
                </group>
                <group
                  name="Plane007"
                  position={[-0.819, 0.167, -0.01]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_31"
                    position={[530.292, 29.795, -50.588]}
                    rotation={[1.572, 0.056, 1.498]}
                  >
                    <mesh
                      name="Plane007_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane007_volume_light_0.geometry}
                      material={materials.volume_light}
                    />
                  </group>
                </group>
                <group
                  name="Plane008"
                  position={[0.879, 0.142, -0.01]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.001}
                >
                  <group
                    name="Object_34"
                    position={[-530.292, 29.795, -50.588]}
                    rotation={[1.572, -0.056, -1.498]}
                    scale={[-1, 1, 1]}
                  >
                    <mesh
                      name="Plane008_volume_light_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane008_volume_light_0.geometry}
                      material={materials.volume_light}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/cube.glb");