/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: YD Visual (https://sketchfab.com/ydvisual)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-animated-japanese-led-neon-sign-fab087c62fc3459a8b7664757d980c28
Title: Cyberpunk animated japanese LED neon sign
*/

import React, { useRef,useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function NeonSign(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../models/neon_sign.glb");
  const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
    actions["Animation"].play()
  });
  
  return (
    <group ref={group} {...props} dispose={null}  scale={0.2}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="LEDn0000_0"
                position={[0, 0, 0.09]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.matLEDn0000}
                />
              </group>
              <group name="LEDn0001_1" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.matLEDn0001}
                />
              </group>
              <group name="LEDn0002_2" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.matLEDn0002}
                />
              </group>
              <group name="LEDn0003_3" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.matLEDn0003}
                />
              </group>
              <group name="LEDn0004_4" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.matLEDn0004}
                />
              </group>
              <group name="LEDn0005_5" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.matLEDn0005}
                />
              </group>
              <group name="LEDn0006_6" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.matLEDn0006}
                />
              </group>
              <group name="LEDn0007_7" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.matLEDn0007}
                />
              </group>
              <group name="LEDn0008_8" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.matLEDn0008}
                />
              </group>
              <group name="LEDn0009_9" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.matLEDn0009}
                />
              </group>
              <group name="LEDn0010_10" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.matLEDn0010}
                />
              </group>
              <group name="LEDn0011_11" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.matLEDn0011}
                />
              </group>
              <group name="LEDn0012_12" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.matLEDn0012}
                />
              </group>
              <group name="LEDn0013_13" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.matLEDn0013}
                />
              </group>
              <group name="LEDn0014_14" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.matLEDn0014}
                />
              </group>
              <group name="LEDn0015_15" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.matLEDn0015}
                />
              </group>
              <group name="Body_16">
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.matBody}
                />
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.matNeon}
                />
              </group>
              <group name="Holder_17" position={[1.6, 0.7, 0]}>
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.matBody}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/neon_sign.glb");
